//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/Scripts/ControlMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scripts/ControlMap.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @ControlMap: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @ControlMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""ControlMap"",
    ""maps"": [
        {
            ""name"": ""JetEngine"",
            ""id"": ""cfed0506-cf36-42c5-8ee4-dc273547e37b"",
            ""actions"": [
                {
                    ""name"": ""ThrottleUp"",
                    ""type"": ""Button"",
                    ""id"": ""88ddfbc5-a03f-41e5-b39f-23212d0ea5f7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThrottleDown"",
                    ""type"": ""Button"",
                    ""id"": ""3e220b57-a53b-4fef-b5cb-4c44ba1b481a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThrottleStepUp"",
                    ""type"": ""Button"",
                    ""id"": ""506d690e-bcdc-4cf5-a041-05a685579042"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThrottleStepDown"",
                    ""type"": ""Button"",
                    ""id"": ""577a78f4-a6c8-420d-8a5f-4d91ea7ef2d2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleAB"",
                    ""type"": ""Button"",
                    ""id"": ""c2b883c5-7a69-42f9-8609-67f6f0feafc2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3ca9a66c-d279-437e-adbc-02e6b2b2f588"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrottleUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77ac7bf7-fb8a-462c-8de8-0005e17da461"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrottleDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6b21620-4150-42c2-aa68-6cdfd7eb80ba"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrottleStepUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""39eff000-1088-4096-a43d-e6b3c4899caa"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrottleStepDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""24921f61-2e77-4711-9084-e73661e73fe4"",
                    ""path"": ""<Keyboard>/leftAlt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleAB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // JetEngine
        m_JetEngine = asset.FindActionMap("JetEngine", throwIfNotFound: true);
        m_JetEngine_ThrottleUp = m_JetEngine.FindAction("ThrottleUp", throwIfNotFound: true);
        m_JetEngine_ThrottleDown = m_JetEngine.FindAction("ThrottleDown", throwIfNotFound: true);
        m_JetEngine_ThrottleStepUp = m_JetEngine.FindAction("ThrottleStepUp", throwIfNotFound: true);
        m_JetEngine_ThrottleStepDown = m_JetEngine.FindAction("ThrottleStepDown", throwIfNotFound: true);
        m_JetEngine_ToggleAB = m_JetEngine.FindAction("ToggleAB", throwIfNotFound: true);
    }

    ~@ControlMap()
    {
        UnityEngine.Debug.Assert(!m_JetEngine.enabled, "This will cause a leak and performance issues, ControlMap.JetEngine.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // JetEngine
    private readonly InputActionMap m_JetEngine;
    private List<IJetEngineActions> m_JetEngineActionsCallbackInterfaces = new List<IJetEngineActions>();
    private readonly InputAction m_JetEngine_ThrottleUp;
    private readonly InputAction m_JetEngine_ThrottleDown;
    private readonly InputAction m_JetEngine_ThrottleStepUp;
    private readonly InputAction m_JetEngine_ThrottleStepDown;
    private readonly InputAction m_JetEngine_ToggleAB;
    /// <summary>
    /// Provides access to input actions defined in input action map "JetEngine".
    /// </summary>
    public struct JetEngineActions
    {
        private @ControlMap m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public JetEngineActions(@ControlMap wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "JetEngine/ThrottleUp".
        /// </summary>
        public InputAction @ThrottleUp => m_Wrapper.m_JetEngine_ThrottleUp;
        /// <summary>
        /// Provides access to the underlying input action "JetEngine/ThrottleDown".
        /// </summary>
        public InputAction @ThrottleDown => m_Wrapper.m_JetEngine_ThrottleDown;
        /// <summary>
        /// Provides access to the underlying input action "JetEngine/ThrottleStepUp".
        /// </summary>
        public InputAction @ThrottleStepUp => m_Wrapper.m_JetEngine_ThrottleStepUp;
        /// <summary>
        /// Provides access to the underlying input action "JetEngine/ThrottleStepDown".
        /// </summary>
        public InputAction @ThrottleStepDown => m_Wrapper.m_JetEngine_ThrottleStepDown;
        /// <summary>
        /// Provides access to the underlying input action "JetEngine/ToggleAB".
        /// </summary>
        public InputAction @ToggleAB => m_Wrapper.m_JetEngine_ToggleAB;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_JetEngine; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="JetEngineActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(JetEngineActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="JetEngineActions" />
        public void AddCallbacks(IJetEngineActions instance)
        {
            if (instance == null || m_Wrapper.m_JetEngineActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_JetEngineActionsCallbackInterfaces.Add(instance);
            @ThrottleUp.started += instance.OnThrottleUp;
            @ThrottleUp.performed += instance.OnThrottleUp;
            @ThrottleUp.canceled += instance.OnThrottleUp;
            @ThrottleDown.started += instance.OnThrottleDown;
            @ThrottleDown.performed += instance.OnThrottleDown;
            @ThrottleDown.canceled += instance.OnThrottleDown;
            @ThrottleStepUp.started += instance.OnThrottleStepUp;
            @ThrottleStepUp.performed += instance.OnThrottleStepUp;
            @ThrottleStepUp.canceled += instance.OnThrottleStepUp;
            @ThrottleStepDown.started += instance.OnThrottleStepDown;
            @ThrottleStepDown.performed += instance.OnThrottleStepDown;
            @ThrottleStepDown.canceled += instance.OnThrottleStepDown;
            @ToggleAB.started += instance.OnToggleAB;
            @ToggleAB.performed += instance.OnToggleAB;
            @ToggleAB.canceled += instance.OnToggleAB;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="JetEngineActions" />
        private void UnregisterCallbacks(IJetEngineActions instance)
        {
            @ThrottleUp.started -= instance.OnThrottleUp;
            @ThrottleUp.performed -= instance.OnThrottleUp;
            @ThrottleUp.canceled -= instance.OnThrottleUp;
            @ThrottleDown.started -= instance.OnThrottleDown;
            @ThrottleDown.performed -= instance.OnThrottleDown;
            @ThrottleDown.canceled -= instance.OnThrottleDown;
            @ThrottleStepUp.started -= instance.OnThrottleStepUp;
            @ThrottleStepUp.performed -= instance.OnThrottleStepUp;
            @ThrottleStepUp.canceled -= instance.OnThrottleStepUp;
            @ThrottleStepDown.started -= instance.OnThrottleStepDown;
            @ThrottleStepDown.performed -= instance.OnThrottleStepDown;
            @ThrottleStepDown.canceled -= instance.OnThrottleStepDown;
            @ToggleAB.started -= instance.OnToggleAB;
            @ToggleAB.performed -= instance.OnToggleAB;
            @ToggleAB.canceled -= instance.OnToggleAB;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="JetEngineActions.UnregisterCallbacks(IJetEngineActions)" />.
        /// </summary>
        /// <seealso cref="JetEngineActions.UnregisterCallbacks(IJetEngineActions)" />
        public void RemoveCallbacks(IJetEngineActions instance)
        {
            if (m_Wrapper.m_JetEngineActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="JetEngineActions.AddCallbacks(IJetEngineActions)" />
        /// <seealso cref="JetEngineActions.RemoveCallbacks(IJetEngineActions)" />
        /// <seealso cref="JetEngineActions.UnregisterCallbacks(IJetEngineActions)" />
        public void SetCallbacks(IJetEngineActions instance)
        {
            foreach (var item in m_Wrapper.m_JetEngineActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_JetEngineActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="JetEngineActions" /> instance referencing this action map.
    /// </summary>
    public JetEngineActions @JetEngine => new JetEngineActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "JetEngine" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="JetEngineActions.AddCallbacks(IJetEngineActions)" />
    /// <seealso cref="JetEngineActions.RemoveCallbacks(IJetEngineActions)" />
    public interface IJetEngineActions
    {
        /// <summary>
        /// Method invoked when associated input action "ThrottleUp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnThrottleUp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ThrottleDown" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnThrottleDown(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ThrottleStepUp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnThrottleStepUp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ThrottleStepDown" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnThrottleStepDown(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ToggleAB" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnToggleAB(InputAction.CallbackContext context);
    }
}
